USE Game_Store;

--Creación de rol y permisos para administrador.
CREATE ROLE "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON usuario TO "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON videojuego TO "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON calificacion TO "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON clasificacion TO "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON contacto_publisher TO "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON detalle_ord_compra TO "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON detalle_wishlist TO "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON factura TO "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON genero TO "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON ord_compra TO "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON publisher TO "ADMIN";
GRANT SELECT, INSERT, UPDATE, DELETE ON wishlist TO "ADMIN";



